FROM python:3.11-slim

WORKDIR /app

# Install OS dependencies needed by OpenCV for GUI
RUN apt-get update && \
    apt-get install -y libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "onnx-inference.py"]